from antlr4 import Lexer
from antlr4.error.ErrorListener import ErrorListener

class wizardLexer(Lexer):
    COMMENT: int = ...
    CONTINUATION: int = ...
    Comma: int = ...
    Dot: int = ...
    LeftParenthesis: int = ...
    RightParenthesis: int = ...
    LeftBracket: int = ...
    RightBracket: int = ...
    Colon: int = ...
    CompoundAdd: int = ...
    CompoundSub: int = ...
    CompoundMul: int = ...
    CompoundDiv: int = ...
    CompoundExp: int = ...
    CompoundMod: int = ...
    Equal: int = ...
    GreaterOrEqual: int = ...
    Greater: int = ...
    LesserOrEqual: int = ...
    Lesser: int = ...
    NotEqual: int = ...
    Assign: int = ...
    Break: int = ...
    Continue: int = ...
    Elif: int = ...
    Else: int = ...
    EndFor: int = ...
    EndIf: int = ...
    EndSelect: int = ...
    EndWhile: int = ...
    Return: int = ...
    Keyword: int = ...
    Number: int = ...
    DoubleQuotedString: int = ...
    SingleQuotedString: int = ...
    Divide: int = ...
    Minus: int = ...
    Plus: int = ...
    Raise: int = ...
    Times: int = ...
    Modulo: int = ...
    Decrement: int = ...
    In: int = ...
    Increment: int = ...
    Identifier: int = ...
    WHITESPACE: int = ...

    def addErrorListener(self, listener: ErrorListener) -> None: ...
    def removeErrorListener(self, listener: ErrorListener) -> None: ...
    def removeErrorListeners(self) -> None: ...
